### ISSUE TITLE
Geen onderwerp.

### ISSUE THREAD

**Issue by beauterre** [nickmeijer2110/MyBand#1]
Readme (als debriefing) goed, nu verder
Ik mis nog een onderwerp.
Ik mis nog de documentatie.
-Debriefing.. dus wat er in de readme staat + iets meer info over de pagina's
-moodboard + concurrentieonderzoek.
-F.O.
Ik wil deze week het F.O kunnen goedkeuren.
Ik volg je github, dus ik zie het wel verschijnen.

**Comment by nickmeijer2110** [comment]
Ik heb de documentatie toegevoegd! Sorry dat het zo lang duurde, was het helemaal vergeten.

**Comment by beauterre** [comment]
Geen probleem, net op tijd voor de peer-review..
